### ISSUE TITLE
Kakao SDK error

### ISSUE THREAD

**Issue by awadeyar** [lihak/KakaoTalkCordovaPlugin#1]
inside the kakao plugin java class. I am getting KAKASDK  not found error and import com.kakao.Auth errors.

**Comment by awadeyar** [comment]
Error 
"Error:(17, 22) package com.kakao.auth does not exist
Error:(18, 22) package com.kakao.auth does not exist
Error:(19, 22) package com.kakao.auth does not exist
Error:(20, 22) package com.kakao.auth does not exist
Error:(21, 22) package com.kakao.auth does not exist
Error:(22, 22) package com.kakao.auth does not exist
Error:(23, 22) package com.kakao.auth does not exist
Error:(24, 22) package com.kakao.auth does not exist
Error:(25, 22) package com.kakao.auth does not exist
Error:(26, 26) package com.kakao.usermgmt does not exist
Error:(27, 35) package com.kakao.usermgmt.callback does not exist
Error:(28, 35) package com.kakao.usermgmt.callback does not exist
Error:(29, 41) package com.kakao.usermgmt.response.model does not exist
Error:(30, 35) package com.kakao.usermgmt.callback does not exist
Error:(31, 32) package com.kakao.util.exception does not exist
Error:(148, 46) cannot find symbol class ISessionCallback
Error:(129, 37) cannot find symbol class UserProfile
Error:(184, 41) cannot find symbol class KakaoException
Error:(211, 50) cannot find symbol class KakaoAdapter
Error:(214, 16) cannot find symbol class ISessionConfig
Error:(239, 16) cannot find symbol class IApplicationConfig
Error:(49, 9) cannot find symbol variable KakaoSDK
Error:(63, 9) cannot find symbol variable Session
Error:(85, 50) cannot find symbol variable AuthType
Error:(85, 17) cannot find symbol variable Session
Error:(99, 50) cannot find symbol class LogoutResponseCallback
Error:(99, 17) cannot find symbol variable UserManagement
Error:(119, 13) cannot find symbol variable Session
Error:(159, 42) cannot find symbol class MeResponseCallback
Error:(159, 13) cannot find symbol variable UserManagement
Error:(156, 9) method does not override or implement a method from a supertype
Error:(183, 9) method does not override or implement a method from a supertype
Error:(215, 24) cannot find symbol class ISessionConfig
Error:(213, 9) method does not override or implement a method from a supertype
Error:(240, 24) cannot find symbol class IApplicationConfig
Error:(238, 9) method does not override or implement a method from a supertype
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
100 warnings
Error:Execution failed for task ':compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details."

**Comment by lihak** [comment]
Did you run the following command?
1. cordova plugin add https://github.com/lihak/KakaoTalkCordovaPlugin --variable KAKAO_APP_KEY=%KAKAO_APP_KEY%
2. cordova build android

Check your Explorer
![github_1](https://cloud.githubusercontent.com/assets/1587168/12288592/feb83f86-ba18-11e5-89cd-422fa0f4ced0.png)

![github_2](https://cloud.githubusercontent.com/assets/1587168/12288600/08fd6a3e-ba19-11e5-959f-de426da230f8.png)

**Comment by awadeyar** [comment]
Thanks for the reply.

I followed the both steps. But it didn't create the com.kakao.sdk in builds----> intermediates---->exploded.aar
Check the screenshot attached.
![screen shot 2016-01-13 at 5 57 39 pm]

(https://cloud.githubusercontent.com/assets/12082080/12294299/372e0bce-ba1f-11e5-96e0-fefd6405eff5.png)

Regards,
awadeyar

**Comment by lihak** [comment]
Please tell me the results after the next step:
1. cd .. // Safety First ;-)
2. cordova create TestApp
4. cd TestApp
5. cordova platform add android
6. cordova plugin add https://github.com/lihak/KakaoTalkCordovaPlugin --variable KAKAO_APP_KEY=%KAKAO_APP_KEY%
7. cordova build android

Good luck!

**Comment by awadeyar** [comment]
Hi Lihak,

Tried the above steps but still the problem persists.
Can we add the kakao sdk manually to the project?
Please refer the screenshot for errors 
![screen shot 2016-01-14 at 10 47 41 am](https://cloud.githubusercontent.com/assets/12082080/12316416/52d41b7e-baac-11e5-9e41-1fcc573db91c.png)

I tried adding Kakaosdk as module and I was successful adding sdk. But after that same error.

**Comment by lihak** [comment]
Hi Awadeyar,

Look at the file 'kakao.gradle' (https://github.com/lihak/KakaoTalkCordovaPlugin/blob/master/src/android/kakao.gradle)
The maven url is what you want.
But i recommend that you move the file 'kakao.gradle'  to 'platforms/android/' folder first,
and rename it to 'build-extras.gradle'.

I hope you will now be able to get the kakao-sdk.
cordova build android

**Comment by awadeyar** [comment]
Hi Lihak,

Getting this error

E/kakao.sdk: WebViewAuthHandler is failed
                                                           java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                               at android.os.Handler.<init>(Handler.java:200)
                                                               at android.os.Handler.<init>(Handler.java:114)
                                                               at android.app.Dialog.<init>(Dialog.java:113)
                                                               at android.app.Dialog.<init>(Dialog.java:155)
                                                               at com.kakao.auth.authorization.authcode.KakaoWebViewDialog.<init>(KakaoWebViewDialog.java:84)
                                                               at com.kakao.auth.authorization.authcode.GetterAuthCode.requestWebviewAuth(GetterAuthCode.java:197)
                                                               at com.kakao.auth.authorization.authcode.GetterAuthCode.request(GetterAuthCode.java:165)
                                                               at com.kakao.auth.authorization.authcode.GetterAuthCode.start(GetterAuthCode.java:96)
                                                               at com.kakao.auth.Session.requestAuthCode(Session.java:537)
                                                               at com.kakao.auth.Session.internalOpen(Session.java:509)
                                                               at com.kakao.auth.Session.open(Session.java:139)
                                                               at com.lihak.plugin.kakao.KakaoTalk$1.run(KakaoTalk.java:83)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by lihak** [comment]
Hi awadeyar,

Thanks for the error report.
I have changed the thread of "KakaoTalk" class.
Look at https://github.com/lihak/KakaoTalkCordovaPlugin/commit/297f7d04dc404394e2c543bce5b77b4c8a395764

**Comment by awadeyar** [comment]
Thanks lihak.
But still I have the problem with login.
It will popup the login dialog and I can login. But the login function is not returning any thing.
It just closes the login dialog.
Getting this error.
![screen shot 2016-01-21 at 6 23 17 pm](https://cloud.githubusercontent.com/assets/12082080/12480973/1e798326-c06c-11e5-92f1-1b275a91e7d8.png)

Thanks,
awadeyar

**Comment by lihak** [comment]
https://developers.kakao.com/
1. Check 'Native app key' of your application.
2. Android app must register key hash(https://developers.kakao.com/docs/android#getting-started-launch-sample-app) : keytool -exportcert -alias androiddebugkey -keystore debug_keystore_path -storepass android -keypass android | openssl sha1 -binary | openssl base64
3. Look at LogCat

Regards,
Lihak
