### ISSUE TITLE
카카오 로그인시에 image 가 null 일경우 오류 발생합니다.

### ISSUE THREAD

**Issue by water0126** [lihak/KakaoTalkCordovaPlugin#2]
@"profile_image": [result propertyForKey:@"profile_image"] };

아래로 변경 부탁 드립니다.

 @"profile_image": [result propertyForKey:@"profile_image"] != nil ?  [result propertyForKey:@"profile_image"] : @""};

android 일경우는 아직 확인 안해 봤어요.~

**Comment by lihak** [comment]
감사합니다!
https://github.com/lihak/KakaoTalkCordovaPlugin/blob/master/src/ios/KakaoTalk.m
