### ISSUE TITLE
안녕하세요 개발자님!! 질문하나만 드려도 될까요!ㅠㅠ

### ISSUE THREAD

**Issue by stmake22** [lihak/KakaoTalkCordovaPlugin#4]
원래 안드로이드만 계약해서 개발하던도중 iOS를 추가개발하게 되었습니다.
iOS는 C언어 같은데
마찬가지로 토큰을 얻어오기위해 제가 소스를 잠깐 봤는데(C언어는 거희 전혀 할줄모릅니다 ㅠㅠ)
                   NSDictionary *userSession = @{
                                          @"id": result.ID,
                                          @"nickname": [result propertyForKey:@"nickname"],
                                          @"profile_image": [result propertyForKey:@"profile_image"]};

아마 여기서 받아서 자바스크립트로 넘겨줘야하는듯 한데
시간 나시면 저번처럼 간단하게 설명해주실수 있으실까요!? ㅠㅅㅠ
저번에 정말 도움이 많이 되었습니다. 덕분에 1차프로젝트를 무사히 마칠수 있었습니다!
아 그리구 kakaoiOS SDK를 깔아야하는거죠?
appDelegate 에 추가하는 코드는 어떤파일에 추가하는거죠?

#import "AppDelegate.h"
#import "MainViewController.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
{
    self.viewController = [[MainViewController alloc] init];
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end

appDelegate.m 파일인데 여기에 어떻게 추가해야하는거죠?

위의 질문
                    NSDictionary *userSession = @{
                                          @"id": result.ID,
                                          @"nickname": [result propertyForKey:@"nickname"],
                                          @"profile_image": [result propertyForKey:@"profile_image"],
                                          @"authToken": [KOSession sharedSession].accessToken};
이런식으로 받아오는게 맞나요?

**Comment by lihak** [comment]
오랜만입니다.^^
closed 하신 것으로 보아 해결이 된 것 같네요.

**Comment by stmake22** [comment]
넵넵 ㅠㅠ하지만 ios inapp  purchase 때문에 다시 골머리를 썩고있습니다.연말 잘보네세용!
------ Original Message ------
Date: Thursday, Dec 15, 2016 12:35:25 AM
